{% set conda_version = "24.7.1" %}
{% set conda_libmamba_solver_version = "24.7.0" %}
{% set libmambapy_version = "1.5.8" %}
{% set constructor_version = "3.9.2" %}
{% set menuinst_lower_bound = "2.1.2" %}
{% set python_version = "3.11.9" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ version }}.tar.gz
    sha256: 658c00fab9a117c4712592cf6891d752cfd404dd3c0afbb9bfc51514f884ceba

  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 8590451bc4527ec6a2ca48242c940f2e6d5ea60972702d5671ac2299fab63e6f
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 0ea4f6d563a53ebb03475dc6d2d88d3ab01be4e9d291fd276c79315aa92e5114  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - {{ stdlib('c') }}  # [osx and x86_64]
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
    - menuinst >={{ menuinst_lower_bound }}
  source_files:
    - tests
  commands:
    - pytest -vv
    - test ! -f {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
